### ISSUE TITLE
[Documentation] How to update the vendor ID? 

### ISSUE THREAD

**Issue by lecontr2** [ambiot/ambd_matter#111]
Hello! I'm looking to update the vendor ID attribute within the sample applications but I cannot find any information regarding the source of this Identifier value. Do you have additional information as to where I can set it?

**Comment by xshuqun** [comment]
Hi @lecontr2, you can check our Application Notes in the SDK. https://github.com/ambiot/ambd_matter/blob/main/doc/AN0204%20Realtek%20Matter%20application%20note.en.pdf
In Chapter 10, we had introduced about Matter Certification Generation and Factory Data. Since the Matter certificate and VID/PID are related, when the VID/PID changes, a new certificate must be generated. 
You can either use Factory Data (Chapter 10.3) or hardcode (Chapter 10.4) the certificates + VID/PID into the SDK.

**Comment by lecontr2** [comment]
Excellent! Thank you for the resource! I'll give that a look. 😄
